### ISSUE TITLE
[DB] employees_tokens

### ISSUE THREAD

**Issue by jurciusmantas** [jurciusmantas/PSK#51]
id, employee_id, token, created_at, expires_at 

token - varchar
created_at, expires_at - timestamp

**Comment by mr-frying-pan** [comment]
`expires_at` gal nereikia. Manau, užtektų `created_at` ir kada expires galim paskaičiuot

**Comment by lukasbaltramaitis** [comment]
> `expires_at` gal nereikia. Manau, užtektų `created_at` ir kada expires galim paskaičiuot

Su expires_at: 1) Nuskaitom expires_at; 2) Paimame dabartinį laiką; 3) Palyginame;
Be expires_at: 1) Nuskaitome created_at: 2) Paimame dabartinį laiką; 3) Pridedame numatytą laiką prie created_at; 4) Palyginame; 

Daugiau laisvės turime, kai yra expires_at, todėl manau turime jį pridėti. Jeigu tai nepasitesins išmesime.
