### ISSUE TITLE
[BACK] Create SessionData service

### ISSUE THREAD

**Issue by jurciusmantas** [jurciusmantas/PSK#71]
Reiktų turėti tokį servisą, kad iš betkurios sistemos vietos galėtume jį įsiinject'inti ir turėtume info apie dabar prisijungusį employee. Tokiu būdų nereiktų visokiem veiksmam siuntinėti info (dažniausiai bus employeeId kaip įsivaizduoju, arba login) iš fronto

Tikriausiai šitam reiktų palaukti https://github.com/jurciusmantas/PSK/issues/48 tasko, kad nesusikonfliktuotų perdaug.

**Comment by mr-frying-pan** [comment]
Reiktų dar turėt omeny, kad prie tos pačios sistemos prisijungę vienu metu yra keli žmonės. Kiekvienam turėtų grąžint jo id
